name: dalvicdating
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl_phone_field: ^1.4.2
  flutter_svg: ^0.17.4
  salomon_bottom_bar: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
#  fonts:
#    - family: Pacifico
#      fonts:
#        - asset: fonts/Pacifico-Regular.ttf
#
#    - family: SourceSansPro
#      fonts:
#        - asset: fonts/SourceSansPro-Regular.ttf
